### ISSUE TITLE
handle empty response from infinitude api

### ISSUE THREAD

**Issue by jeremyhayes** [jeremyhayes/infinitude-prometheus#3]
```
q26065z2ck7m@lab-pi-01    | 2022/04/14 14:43:48 Starting http server on :8080...
q26065z2ck7m@lab-pi-01    | 2022/04/14 14:43:48 Monitoring Infinitude instance at http://infinitude:3000
q26065z2ck7m@lab-pi-01    | panic: runtime error: index out of range [0] with length 0
q26065z2ck7m@lab-pi-01    |
q26065z2ck7m@lab-pi-01    | goroutine 34 [running]:
q26065z2ck7m@lab-pi-01    | github.com/jeremyhayes/infinitude-prometheus/collectors.(*energyCollector).Collect(0x1c6e1e0, 0x1d8d1c0)
q26065z2ck7m@lab-pi-01    | 	/app/source/collectors/energy.go:173 +0xeb8
q26065z2ck7m@lab-pi-01    | github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
q26065z2ck7m@lab-pi-01    | 	/go/pkg/mod/github.com/prometheus/client_golang@v1.12.1/prometheus/registry.go:446 +0x100
q26065z2ck7m@lab-pi-01    | created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
q26065z2ck7m@lab-pi-01    | 	/go/pkg/mod/github.com/prometheus/client_golang@v1.12.1/prometheus/registry.go:538 +0x9b4
```

```
$ curl https://***/energy.json
{}
```

**Comment by jeremyhayes** [comment]
5da4d65c277bbfc6a967946516eeb8eff0a7e0ee
